package com.learning.restate.with.boot.handlers.dto

import com.learning.restate.with.boot.domain.Order
import com.learning.restate.with.boot.domain.OrderEvent

/**
 * Data transfer object representing a request to handle order state changes.
 *
 * This DTO encapsulates the information needed by change handlers to process
 * events generated by the order aggregate.
 *
 * @property aggregateKey The unique identifier of the order being processed
 * @property currentState The current state of the order before applying events
 * @property events The list of events that were generated and need to be processed
 */
data class ChangeHandlerRequest(
    val aggregateKey: String,
    val currentState: Order?,
    val events: List<OrderEvent>
)
