package com.learning.restate.with.boot.gateway.dto

import com.learning.restate.with.boot.domain.LineItem
import com.learning.restate.with.boot.domain.Order
import com.learning.restate.with.boot.domain.OrderEvent
import com.learning.restate.with.boot.domain.readmodel.OrderSummary

/**
 * DTOs for REST API communication
 *
 * Contains request and response data classes for order management endpoints.
 */

/**
 * Request DTO for creating a new order
 *
 * @property id Optional unique identifier for the order. If not provided, a UUID will be generated
 * @property customerId Identifier of the customer placing the order
 * @property items List of line items in the order
 */
data class CreateOrderRequest(
    val id: String? = null,
    val customerId: String,
    val items: List<LineItem>
)

/**
 * Request DTO for shipping an order
 *
 * @property trackingNumber Tracking number for the shipment
 */
data class ShipOrderRequest(
    val trackingNumber: String
)

/**
 * Request DTO for cancelling an order
 *
 * @property reason Reason for cancelling the order
 */
data class CancelOrderRequest(
    val reason: String
)

/**
 * Response DTO for order operations
 *
 * @property success Whether the operation was successful
 * @property orderId Identifier of the order that was processed
 * @property message Human-readable message about the operation result
 * @property order The current state of the order (if available)
 * @property events List of events generated by the operation
 */
data class OrderResponse(
    val success: Boolean,
    val orderId: String,
    val message: String,
    val order: Order? = null,
    val events: List<OrderEvent> = emptyList()
)

/**
 * Response DTO for retrieving a list of orders
 *
 * @property orders List of order summaries
 */
data class OrderListResponse(
    val orders: List<OrderSummary>
)

/**
 * Response DTO for error responses
 *
 * @property error Error type or category
 * @property message Human-readable error message
 * @property details Additional error details (optional)
 */
data class ErrorResponse(
    val error: String,
    val message: String,
    val details: String? = null
)
