package com.learning.restate.with.boot.gateway.dto

import com.learning.restate.with.boot.domain.LineItem
import com.learning.restate.with.boot.domain.Order
import com.learning.restate.with.boot.domain.OrderEvent
import com.learning.restate.with.boot.domain.readmodel.OrderSummary

/**
 * DTO for creating a new order request.
 *
 * This class represents the data structure expected when creating a new order
 * through the REST API.
 *
 * @property id Optional unique identifier for the order. If not provided, one will be generated.
 * @property customerId Identifier of the customer placing the order
 * @property items List of line items to include in the order
 */
data class CreateOrderRequest(
    val id: String? = null,
    val customerId: String,
    val items: List<LineItem>
)

/**
 * DTO for shipping an order request.
 *
 * This class represents the data structure expected when shipping an order
 * through the REST API.
 *
 * @property trackingNumber Tracking number for the shipment
 */
data class ShipOrderRequest(
    val trackingNumber: String
)

/**
 * DTO for cancelling an order request.
 *
 * This class represents the data structure expected when cancelling an order
 * through the REST API.
 *
 * @property reason Reason for cancelling the order
 */
data class CancelOrderRequest(
    val reason: String
)

/**
 * Response DTO for individual order operations.
 *
 * This class represents the data structure returned for order operations
 * through the REST API.
 *
 * @property success Whether the operation was successful
 * @property orderId Identifier of the order being operated on
 * @property message Human-readable message about the operation result
 * @property order The current state of the order, if available
 * @property events List of events generated by the operation
 */
data class OrderResponse(
    val success: Boolean,
    val orderId: String,
    val message: String,
    val order: Order? = null,
    val events: List<OrderEvent> = emptyList()
)

/**
 * Response DTO for listing orders.
 *
 * This class represents the data structure returned when listing all orders
 * through the REST API.
 *
 * @property orders List of order summaries
 */
data class OrderListResponse(
    val orders: List<OrderSummary>
)

/**
 * Response DTO for error conditions.
 *
 * This class represents the data structure returned when an error occurs
 * during API operations.
 *
 * @property error Error category or type
 * @property message Human-readable error message
 * @property details Additional details about the error, if available
 */
data class ErrorResponse(
    val error: String,
    val message: String,
    val details: String? = null
)