package com.learning.restate.with.boot.handlers.port

import com.learning.restate.with.boot.domain.Order
import com.learning.restate.with.boot.domain.OrderEvent
import dev.restate.sdk.kotlin.Context

/**
 * Interface defining the contract for handling state changes in the order system.
 *
 * Implementations of this interface process events that have been generated by
 * the order aggregate and apply side effects such as updating read models,
 * sending notifications, or coordinating with external systems.
 */
interface ChangeHandler {
    /**
     * Handle state changes by processing generated events.
     *
     * @param ctx Restate context for the current invocation
     * @param aggregateKey The unique identifier of the order being processed
     * @param currentState The current state of the order before applying events
     * @param events The list of events that were generated and need to be processed
     */
    suspend fun handleChange(
        ctx: Context,
        aggregateKey: String,
        currentState: Order?,
        events: List<OrderEvent>
    )
}
